version: '3'
services:
  consul:
    image: consul
    ports:
      - '8500:8500'

  patroni:
    build: .
    image: sycured/nomad-pgsql-patroni:latest
    environment:
      PGDATA: /alloc/data
    ports:
      - '5433:5432'
    tmpfs:
      - /alloc
    volumes:
      - './example-patroni.yml:/secrets/patroni.yml'
