version: '3'
services:
  consul:
    image: consul
    ports:
      - '8500:8500'

  patroni:
    build: .
    image: sycured/nomad-pgsql-patroni:latest
    environment:
      PGDATA: /alloc/data
    ports:
      - '5433:5432'
    tmpfs:
      - /alloc
    volumes:
      - './example-patroni.yml:/etc/patroni/config.yml:Z'
      - './files/pgsodium_getkey_urandom.sh:/usr/pgsql-15/share/extension/pgsodium_getkey:Z'
